services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      NODE_ENV: development
    tty: true
